# This file was copied and then modified from here:
# https://gitlab.com/r-packages/limonaid/-/raw/dev/.gitlab-ci.yml
# and
# https://stackoverflow.com/a/71340879
variables:
  _R_CHECK_CRAN_INCOMING_: "true"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git libxt6"

image: rocker/tidyverse

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends ${APT_PKGS}
  - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  - R -e 'install.packages(c("testthat", "rmarkdown"));'
  # install all packages in description file not yet installed:
  - R -e 'install.packages(setdiff(desc::desc()$get_deps()$package, c(installed.packages(), "R")));'

devtools-check:
  stage: build
  script:
    - R -e 'devtools::check()'

pages:
  stage: build
  script:
  - R -e "devtools::document(); pkgdown::build_site()"
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
