---
title: "Untitled"
output: html_document
date: '2022-08-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(datenanpassr)
library(dplyr)
library(gt)
```


```{r}
command_block_classes %>% gt()
```

## #drp
```{r}
command_block_doc_helper <- function(dat, cdb_args) {
  cdb_args_raw <- tibble(X1 = "#VARL", X2 = "x", X3 = "assigned variable label")
  cdb_class <- command_block_classes[command_block_classes$keyword == cdb_args_raw$X1[1], ][["command_block"]]
  print("Taking this original dataset:")
  dat %>% print()
  print("... and this command block:")
  cdb_args_raw %>% print()
  class(cdb_args_raw) <- c(cdb_class, class(cdb_args_raw))
  cdb_args <- cdb_args_raw %>% parse_command_args()
  print("When such a command block is passed to parse_command_args(), it results in the following arguments:")
  print(cdb_args)
  # cdb_class <- command_block_classes[command_block_classes$keyword == keyword, ][["command_block"]]
  m0 <- Mapping$new()
  m0$dat_mod <- dat
  
  arg_list <- list(
    cdb = structure(
      list(),
      class = cdb_class
    ),
    mapping = m0
  ) %>% append(
    cdb_args
  )
  do.call(apply_command, arg_list)  
  print("When we apply the command block on the data, it results in this modified data:")
  m0$dat_mod
}
```

```{r}
# mapping_file <- system.file("extdata", "mapping.xlsx", package = "datenanpassr")
# spss_file <- system.file("extdata", "fake_survey.sav", package = "datenanpassr")
# dat <- tibble(id = 1:3, x = 4:6)
# dat
# 
# cdb_args <- list(
#     xs = "x"
#   )
# 
# command_block_doc_helper("#DROP", dat, cdb_args)


```

```{r}
dat <- tibble(id = 1:3, x = 4:6)

cdb_args_raw <- tibble(X1 = "#VARL", X2 = "x", X3 = "assigned variable label")

res <- command_block_doc_helper(dat, cdb_args_raw)
res
res$x
```

