---
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(datadaptor)
```

```{r}
mapping_file <- "tests/testthat/excel/mapping_old.xlsx" |> here::here()
spss_file <- "tests/testthat/spss/fake_survey.sav" |> here::here()
bench::mark(datadaptor::Mapping$new(spss_file, mapping_file), min_iterations = 7)
```

```{r}
# use_openxlsx <- function(filename = system.file("extdata", "mapping_xlsm.xlsx", package = "datadaptor")) {
#   # wb <- openxlsx::loadWorkbook(filename)
#   # map(wb$sheet_names, ~ openxlsx::readWorkbook(wb, .x))
#   openxlsx::readWorkbook(filename, "Free1", cols = 1:5, skipEmptyRows = FALSE)
# }
# 
#   # readxl::excel_sheets(filename) |> map(~ readxl::read_xlsx(filename, .x))
#   readxl::read_xlsx(filename, "Free1", range = readxl::cell_cols(1:5))
# }
# bench::mark(
#   use_openxlsx(),
#   use_readxl(),
#   check = FALSE
# )




# press -------------------------------------------------------------------
wb <- openxlsx::loadWorkbook(mapping_file)
use_openxlsx <- function(filename = mapping_file, sheet) {
  # wb <- openxlsx::loadWorkbook(filename)
  # map(wb$sheet_names, ~ openxlsx::readWorkbook(wb, .x))
  openxlsx::readWorkbook(wb, sheet, cols = 1:5, skipEmptyRows = FALSE)
}

use_readxl <- function(filename = mapping_file, sheet) {
  # readxl::excel_sheets(filename) |> map(~ readxl::read_xlsx(filename, .x))
  readxl::read_xlsx(filename, sheet, range = readxl::cell_cols(1:5))
}

bm <- bench::press(
  sheet = readxl::excel_sheets(mapping_file),
  bench::mark(
    use_openxlsx(sheet = sheet),
    use_readxl(sheet = sheet),
    min_iterations = 7,
    check = FALSE
  )
)
print(bm, n = 111)
bench::mark(wb <- openxlsx::loadWorkbook(mapping_file))
bm |> group_by(expression) |> summarise(sum(median))
bm |>
  ggplot2::ggplot() +
  aes(x = as_factor(expression |> as.character()), y = median, color = sheet, group = sheet) +
  geom_point() +
  geom_line() +
  gghighlight::gghighlight(TRUE)

```

```{r}
sheets <- readxl::excel_sheets(mapping_file)

re <- function() {
  sheets |> lapply(\(x) readxl::read_excel(mapping_file, x))
}
re()

ox <- function() {
  wb <- openxlsx::loadWorkbook(mapping_file)
  sheets |> lapply(\(x) openxlsx::read.xlsx(wb, x))
}
ox()
bench::mark(re(), ox(), check = F)
```


# named regions

```{r}
# wb2 <- openxlsx2::wb_load(mapping_file)
# use_openxlsx2 <- function(wb, sheet) {
#   nrs <- openxlsx2::get_named_regions(wb) |>
#     filter(name |> str_detect("^R_")) |>
#     pull(name)
#   map(nrs, ~openxlsx2::read_xlsx(wb, namedRegion = .x, colNames = FALSE))
# }
# # use_openxlsx2(wb2)



wb <- openxlsx::loadWorkbook(mapping_file)
use_openxlsx <- function(filename = mapping_file, sheet) {
  nrs <- openxlsx::getNamedRegions(wb) |> str_subset("^R_")
  nrs |> map(~openxlsx::read.xlsx(wb, namedRegion = .x, colNames = FALSE))
}
# use_openxlsx(wb)

bench::mark(
  use_openxlsx(wb),
  # use_openxlsx2(wb2),
  check = FALSE
)

```

# init mapping 

```{r}
bench::mark(Mapping$new(mapping_file = mapping_file))
```

