---
title: "Untitled"
author: "Urs Wilke"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(datadaptor)
library(tidyverse)
mapping_file <- system.file("extdata", "mapping.xlsx", package = "datadaptor")
spss_file <- system.file("extdata", "fake_survey.sav", package = "datadaptor")
mapping_s3 <- Mapping$new(spss_file, mapping_file)
# filter commands that are already implemented:
cbs <- mapping_s3$cmd$command_blocks
unique_cmd_bloks <- cbs[!duplicated(map_chr(cbs, "action"))]
type_list <-  tibble(
  action = map_chr(unique_cmd_bloks, "action"),
  unique_cmd_bloks %>% 
    map("args") %>% 
    map_dfr(~map(.x, typeof))
)
  
# %>% 
#   mutate(action = unique_cmd_bloks %>% map_chr("action"))
type_list
```

```{r}
names(type_list) %>% sort()
```

```{r}
c("orig_var", "new_var", "var", "orig_vars", "var_ziel", "split_var", 
"by_var", "variable_names")
```

```{r}
c("action", "replace_val", "replace_label", 
"x", "vals_added", "labs_added", "y", "new_lab", "orig_vals", 
"new_vals", "new_labs", "xs", "ys", "new_label", "val_assign", 
"varlab", "vallab", "id_list", "init_val", "new_val", "condition", 
"lb", "ub", "split_var", "by_var", "merge_file", "id", "r_script", 
"fun_name", "r_code")
```

