---
title: "Generate fake survey data"
author: "Urs Wilke"
date: "12/1/2020"
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message=FALSE}
library(dplyr)
library(tibble)
library(purrr)
```

### `command_block_classes` dataset

```{r}
command_block_classes <- tribble(
               ~keyword,        ~command_block,      ~sheet,
                "#RECNA",      "cmd_recna_xcpt",          NA,
                   "#IF",              "cmd_if",      "Free",
                 "#COMP",            "cmd_comp",      "Free",
                 "#VARL",         "cmd_set_lab",      "Free",
                 "#VALL",        "cmd_set_labs",      "Free",
                  "#REC",             "cmd_rec",      "Free",
               "#SUMVAR",          "cmd_sumvar",     "Label",
                "#AVALL",        "cmd_add_labs",      "Free",
                  "#DIC",             "cmd_dic",      "Free",
              "#AUTOREC",         "cmd_autorec", "Variables",
              "#STR2NUM",      "cmd_str_to_num", "Variables",
      "#RENAME_varsheet", "cmd_rename_varsheet", "Variables",
               "#RENAME",          "cmd_rename",      "Free",
                "#MERGE",           "cmd_merge",      "Free",
              "#NEWVALL",         "cmd_newvall",     "Label",
             "#verbatim",        "cmd_verbatim", "Verbatims",
   "cmd_verbatim_custom", "cmd_verbatim_custom", "Verbatims",
                 "#DROP",            "cmd_drop", "Variables",
               "#NEWLAB",          "cmd_newlab", "Variables",
                   "#KG",              "cmd_kg",      "Free",
                 "#RFUN",            "cmd_rfun",      "Free",
                    "#R",               "cmd_r",      "Free",
                "#RMVAL",           "cmd_rmval",      "Free",
              "#ADDFILE",         "cmd_addfile",      "Free",
               "#SELECT",          "cmd_select",      "Free",
               "#FILTER",          "cmd_filter",      "Free",
               "#ACROSS",          "cmd_across",      "Free",
                "#DEBUG",           "cmd_debug",      "Free",
)

usethis::use_data(command_block_classes, overwrite = TRUE)

```

### `fruit_survey` dataset

```{r}
N <- 100
set.seed(111)
mdg_vallabs <- c(`Not selected` = 0, `Selected` = 1)
scale_vallabs <- c(`1 = It's not bad` = 1, `2` = 2, `3` = 3, `4` = 4, `5 = I love it` = 5)
fruit_survey_labels <- tibble::tribble(
    ~var,                   ~varlab, ~vallabs,
    "id", "ID variable", c(),
   "q1",       "Do you like fruits?", c(`Yes` = 1, `No` = 2, `No answer` = 99),
   "q2_1", "Which fruits do you like? - Apple", mdg_vallabs,
   "q2_2", "Which fruits do you like? - Banana", mdg_vallabs,
   "q2_3", "Which fruits do you like? - Orange", mdg_vallabs,
   "q2_97", "Which fruits do you like? - Others", mdg_vallabs,
   "q3_1", "Please rate on a scale from 1 to 5 how much you like this fruit - Apple", scale_vallabs,
   "q3_2", "Please rate on a scale from 1 to 5 how much you like this fruit - Banana", scale_vallabs,
   "q3_3", "Please rate on a scale from 1 to 5 how much you like this fruit - Orange", scale_vallabs,
   "q3_97", "Please rate on a scale from 1 to 5 how much you like this/these fruit(s) - Others", scale_vallabs,
   "q4", "What's your favorite fruit?", c(`Apple` = 1, Banana = 2, Orange = 3, Others = 97, `No answer` = 99),
   "q5", "How many of your favorite fruit do you like to eat?", c(),
)
fruit_survey <- tibble(id = seq_len(N)) |> 
  mutate(
    q1 = sample(c(rep(1, 20), rep(2, 5), 99), N, TRUE),
    q2_1 = ifelse(q1 == 1, sample(c(rep(1, 3), 0), N, TRUE), NA_real_),
    q2_2 = ifelse(q1 == 1, sample(c(rep(1, 3), 0), N, TRUE), NA_real_),
    q2_3 = ifelse(q1 == 1, sample(c(rep(1, 3), 0), N, TRUE), NA_real_),
    q2_97 = ifelse(q1 == 1, sample(c(rep(1, 3), 0), N, TRUE), NA_real_),
    q3_1 = ifelse(q2_1 == 1, sample(1:5, N, TRUE), NA_real_),
    q3_2 = ifelse(q2_2 == 1, sample(1:5, N, TRUE), NA_real_),
    q3_3 = ifelse(q2_3 == 1, sample(1:5, N, TRUE), NA_real_),
    q3_97 = ifelse(q2_97 == 1, sample(1:5, N, TRUE), NA_real_),
  )

df_fav <- fruit_survey |> 
  select(id, q3_1:q3_97) |> 
  tidyr::pivot_longer(-id, names_prefix = "q3_") |> 
  tidyr::drop_na(value) |> 
  mutate(name = name |> as.numeric()) |> 
  summarise(
    n_fruits = n(), 
    q4 = ifelse(n_fruits == 1, NA_real_, sample(c(name[which.max(value)] |> rep(10), 99), 1)), 
    .by = "id"
  )
fruit_survey <- fruit_survey |> left_join(df_fav, by = "id") 
fruit_survey$q5 <- ifelse(
  fruit_survey$q4 %in% 1:97 | fruit_survey$n_fruits == 1, 
  1 + rweibull(N, 1.8, 4) |> round(), 
  NA_real_
)
fruit_survey$n_fruits <- NULL
f <- function(var, varlab, vallabs) {
  haven::labelled(fruit_survey[[var]], label = varlab, labels = vallabs)
}

fruit_survey <- fruit_survey_labels |> 
  pmap_dfc(f) |>
  suppressMessages() |>
  set_names(names(fruit_survey))
```


* use as package dataset and spss file

```{r}
haven::write_sav(fruit_survey, "inst/extdata/fruit_survey.sav")

usethis::use_data(fruit_survey, overwrite = TRUE)
```




### `mtcars_labelled` dataset

* prepare `mtcars_labelled` data

```{r}
mtcar_labels <- tibble::tribble(
    ~var,                   ~varlab, ~vallabs,
   "mpg",       "Miles/(US) gallon", c(),
   "cyl",     "Number of cylinders", c(`4 cylinders` = 4, `6 cylinders` = 6, `8 cylinders` = 8),
  "disp",   "Displacement (cu.in.)", c(),
    "hp",        "Gross horsepower", c(),
  "drat",         "Rear axle ratio", c(),
    "wt",       "Weight (1000 lbs)", c(),
  "qsec",           "1/4 mile time", c(),
    "vs",                  "Engine", c(`V-shaped` = 0, straight = 1),
    "am",            "Transmission", c(automatic = 0, manual = 1),
  "gear", "Number of forward gears", c(`3 gears` = 3, `4 gears` = 4, `5 gears` = 5),
  "carb",   "Number of carburetors", c(
    `1 carburetor`  = 1,
    `2 carburetors` = 2,
    `3 carburetors` = 3,
    `4 carburetors` = 4,
    `5 carburetors` = 5,
    `6 carburetors` = 6,
    `7 carburetors` = 7,
    `8 carburetors` = 8
  ),
)


f <- function(var, varlab, vallabs) {
  haven::labelled(mtcars[[var]], label = varlab, labels = vallabs)
}

mtcars_labelled <- mtcar_labels |> 
  pmap_dfc(f) |>
  suppressMessages() |>
  set_names(names(mtcars)) |>
  mutate(
    id = as.character(1:nrow(mtcars)),
    model = rownames(mtcars), .before = 1)
```

* use as package dataset and spss file

```{r}
haven::write_sav(mtcars_labelled, "inst/extdata/mtcars_labelled.sav")

usethis::use_data(mtcars_labelled, overwrite = TRUE)

```



## old file

```{r}
set.seed(42)
n <- 100


reply_1_5 <- c("not at all" = 1, "a bit" = 2, "normal" = 3, "much" = 4, "very much" = 5, "no answer" = 99)
reply_yn <- c("yes" = 1, "no" = 2, "no answer" = 99)

question_texts <- c(
  "q1" = "How much do you like the product?",
  "q2" = "Do you want to recommend the product?",
  "q3" = "How likely will you go dancing this weekend?",
  "q4" = "How much do you like your friends?",
  "q5" = "How much do you like your best friend?"
)
types <- list(
  reply_1_5,
  reply_yn,
  reply_1_5,
  reply_1_5,
  reply_1_5
)


fake_labelled <- function(n = 100, labels_vec = NULL, label_str = NULL) {
  haven::labelled(
    sample(c(
      unname(labels_vec), NA), 
      size = n, 
      replace = TRUE,
      prob = c(rep(1, length(labels_vec)), 0.2)
    ), 
    labels = labels_vec, 
    label = label_str)
}
# fake_labelled()
enframe(question_texts, "var", "varlab") %>% mutate(types)
```

* generate fake survey dataframe

```{r}
fake_survey <- map2_dfc(
  question_texts,
  types,
  ~fake_labelled(n, .y, label_str = .x)
  ) %>% 
  set_names(names(question_texts))




```

* add free answer string variables

```{r}

generate_bla_vector <- function(answer_text) {
  bla_text <- paste(rep("bla", sample(1:3, 1)), collapse = " ")
  paste(bla_text, sample(answer_text, 1), collapse = " ")
}
chr_vec1 <- map_chr(1:n, ~generate_bla_vector(c("love", "happiness", "joy")))
chr_vec2 <- map_chr(1:n, ~generate_bla_vector(c("sadness", "fear", "anger", "pain")))
q6 <- haven::labelled(chr_vec1, label = "Tell me something positive.")
q7 <- haven::labelled(chr_vec2, label = "Tell me something negative.")
q8 <- haven::labelled(
  sample(x = 1:10, size = n, replace = TRUE) %>% as.character(), 
  label = "A numeric variable in string format."
)
q9 <- rep(NA_real_, times = n)

fake_survey <- fake_survey %>% mutate(id = row_number(), q6, q7, q8, q9)
fake_survey
```


* use as internal dataset and spss file

```{r}
haven::write_sav(fake_survey, "tests/testthat/spss/fake_survey.sav")

# usethis::use_data(fake_survey, overwrite = TRUE, internal = TRUE)

```

