---
title: "Generate fake survey data"
author: "Urs Wilke"
date: "12/1/2020"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message=FALSE}
library(dplyr)
library(tibble)
library(purrr)
```

* prepare fake survey data

```{r}
set.seed(42)
n <- 100


reply_1_5 <- c("not at all" = 1, "a bit" = 2, "normal" = 3, "much" = 4, "very much" = 5, "no answer" = 99)
reply_yn <- c("yes" = 1, "no" = 2, "no answer" = 99)

question_texts <- c(
  "q1" = "How much do you like the product?",
  "q2" = "Do you want to recommend the product?",
  "q3" = "How likely will you go dancing this weekend?",
  "q4" = "How much do you like your friends?",
  "q5" = "How much do you like your best friend?"
)
types <- list(
  reply_1_5,
  reply_yn,
  reply_1_5,
  reply_1_5,
  reply_1_5
)


fake_labelled <- function(n = 100, labels_vec = NULL, label_str = NULL) {
  haven::labelled(
    sample(c(
      unname(labels_vec), NA), 
      size = n, 
      replace = TRUE,
      prob = c(rep(1, length(labels_vec)), 0.2)
    ), 
    labels = labels_vec, 
    label = label_str)
}
# fake_labelled()
enframe(question_texts, "var", "varlab") %>% mutate(types)
```

* generate fake survey dataframe

```{r}
fake_survey <- map2_dfc(
  question_texts,
  types,
  ~fake_labelled(n, .y, label_str = .x)
  ) %>% 
  set_names(names(question_texts))




```

* add free answer string variables

```{r}

generate_bla_vector <- function(answer_text) {
  bla_text <- paste(rep("bla", sample(1:3, 1)), collapse = " ")
  paste(bla_text, sample(answer_text, 1), collapse = " ")
}
chr_vec1 <- map_chr(1:n, ~generate_bla_vector(c("love", "happiness", "joy")))
chr_vec2 <- map_chr(1:n, ~generate_bla_vector(c("sadness", "fear", "anger", "pain")))
q6 <- haven::labelled(chr_vec1, label = "Tell me something positive.")
q7 <- haven::labelled(chr_vec2, label = "Tell me something negative.")
q8 <- haven::labelled(
  sample(x = 1:10, size = n, replace = TRUE) %>% as.character(), 
  label = "A numeric variable in string format."
)
q9 <- rep(NA_real_, times = n)

fake_survey <- fake_survey %>% mutate(id = row_number(), q6, q7, q8, q9)
fake_survey
```


* use as internal dataset and spss file

```{r}
haven::write_sav(fake_survey, "../inst/extdata/fake_survey.sav")

usethis::use_data(fake_survey, overwrite = TRUE)

```

