matrix:
  IMAGE:
    - rocker/verse

when:
  - event: push
    branch: "${CI_REPO_DEFAULT_BRANCH}"
  - event: pull_request
  - event: tag

variables:
  step_branch_env: &branch_env
    - name: branch_env
      image: alpine/git
      commands:
        # 1. Fetch remote branches from the repository
        - BRANCH_ARRAY=$$(git ls-remote https://codeberg.org/urswilke/datadaptor | grep refs/head | sed 's/.*\/heads\///g')

        # 2. Check if the current branch exists in that list
        - |
          if echo "$${BRANCH_ARRAY}" | grep -qxF "$${CI_COMMIT_SOURCE_BRANCH}"; then
            echo "Branch found! Exporting suffix..."
            echo "SUFFIX=@$${CI_COMMIT_SOURCE_BRANCH}" >> $$WOODPECKER_ENV
          else
            echo "Branch not found! Using default..."
            echo "SUFFIX=" >> $$WOODPECKER_ENV
          fi

  step_trigger_ct: &trigger_ct
    - name: trigger_ct
      image: woodpeckerci/plugin-trigger
      depends_on: [prepare_plugin_vars]
      settings:
        # Map the plugin setting 'repositories' straight to our dynamic environment variable
        repositories:
          from_env: PLUGIN_REPOSITORIES
        token:
          from_secret: WOODPECKER_TRIGGER_TOKEN


steps:
  - <<: *branch_env

  # Intermediate workspace compiler step
  - name: prepare_plugin_vars
    image: alpine
    depends_on: [branch_env]
    commands:
      # Woodpecker's trigger plugin automatically searches for environment fields prefixed with 'PLUGIN_'
      - echo "PLUGIN_REPOSITORIES=urswilke/crosstabser$${SUFFIX}" >> $$WOODPECKER_ENV

  - <<: *trigger_ct
