# this workflow maintained at https://codeberg.org/r-codeberg/woodpecker-ci
# please file bug reports and feature requests to help it improve!

matrix:
  IMAGE:
    - rocker/verse

when:
  - event: push
    branch: "${CI_REPO_DEFAULT_BRANCH}"
  - event: pull_request
  - event: tag

variables:
  step_branch_env: &branch_env
    - name: branch_env
      image: ${IMAGE}
      commands:
        - git ls-remote https://codeberg.org/urswilke/datadaptor/
        - echo $CI_COMMIT_SOURCE_BRANCH
        - BRANCH_ARRAY=$$(git ls-remote https://codeberg.org/urswilke/datadaptor | grep refs/head | sed 's/.*\/heads\///g')
        - if printf "%s\n" "${BRANCH_ARRAY[@]}" | grep  -- "$CI_COMMIT_SOURCE_BRANCH"; then   SUFFIX="@$CI_COMMIT_SOURCE_BRANCH"; else   SUFFIX=''  ; fi ; echo $SUFFIX
        - echo "SUFFIX=$${SUFFIX}" >> envvars

  step_trigger_ct: &trigger_ct
    - name: trigger_ct
      commands:
        - source ./envvars
      image: woodpeckerci/plugin-trigger
      depends_on: [branch_env]
      settings:
        repositories:
          - urswilke/crosstabser$${SUFFIX}
        token:
          from_secret: WOODPECKER_TRIGGER_TOKEN
      params:
        - THIS_BRANCH=$${SUFFIX}



steps:
  - <<: *branch_env
  - <<: *trigger_ct

