mapp_cmd_table_ <- function(
  mapping_file,
  ...
) {

  mapping <- as_mapping(
    mapping_file,
    ...
  )

  if (is.null(mapping$df_cmd)) {
    mapping$df_cmd <- build_cmd_table(mapping)
  }

  structure(
    mapping,
    class = c("cmd_table", class(mapping))
  )
}

# Methods to replace the empty data.frames generated by the new_mapping()
# constructor to df_cmd and keep them as is when mapp_cmd_table() was already
# applied (then the subclass "cmd_table" wa added to the mapping object):
#' @rdname mapp_cmd_table
#' @export
as_cmd_table <- function(mapping, ...) {
  UseMethod("as_cmd_table")
}
as_cmd_table.cmd_table <- function(mapping, ...) {
  mapping
}
as_cmd_table.mapping <- function(mapping, ...) {
  mapp_cmd_table_(mapping, ...)
}
#' @export
as_cmd_table.character <- function(mapping, ...) {
  mapping <- as_mapping(mapping)
  as_cmd_table.mapping(mapping, ...)
}


#' Create a summary table of the data modifications list read in from the
#' Excel mapping file
#'
#' @param mapping filename of the Excel mapping file
#' @param ... Arguments passed to `new_mapping()`
#'
#' @return Command table containing the data of the command blocks of the Excel mapping file.
#' @export
#'
#' @examples
#' mapping_file <- system.file("extdata", "mapping.xlsx", package = "datenanpassr")
#' # open this Excel file (that comes with the package) via:
#' \dontrun{
#' utils::browseURL(mapping_file)
#' }
#' mapp_cmd_table(mapping_file)
#' # Add column for R command:
#' mapp_cmd_table(mapping_file, add_r_command_colum = TRUE)
mapp_cmd_table <- function(mapping, ...) {
  mapping <- mapp_cmd_table_(mapping, ...)
  mapping$df_cmd
}



build_cmd_table <- function(mapping) {
  na_to_filter <- mapping$na_to_filter
  add_r_command_colum <- mapping$add_r_command_colum
  vectorized <- mapping$vectorized
  sheet_cats <- mapping$sheet_cats
  id_var <- mapping$id_var
  df_cmd_manip_string <- mapping$mapping_file_attrs$manipulate_command_table
  df_cmd <- purrr::map2_dfr(
    sheet_cats$sheet %>%
      purrr::set_names(),
    sheet_cats$sheet_type,
    ~ generate_sheet_cmd_table(mapping$mapping_file, .y, .x),
    .id = "sheet"
  )
  if (!is.na(df_cmd_manip_string)) {
    df_cmd <- apply_df_cmd_manip(df_cmd_manip_string, df_cmd)
  }
  df_cmd <- df_cmd %>%
    dplyr::rowwise() %>%
    dplyr::mutate(data = parse_cmd_block_args(.data$action, .data$data, vectorized)) %>%
    dplyr::ungroup()
  if (na_to_filter == TRUE) {
    df_cmd <- dplyr::bind_rows(
      generate_rec_na_cmd_table(mapping),
      df_cmd
    )
  }
  if (add_r_command_colum) {
    cmd_list <- purrr::map2(df_cmd$action, df_cmd$data, ~deparse(generate_cmd_expression(.x, .y)))
    df_cmd["R command"] <-
      tibble::tibble(a = cmd_list) %>%
      dplyr::rowwise() %>%
      dplyr::mutate(a = list(paste(stringr::str_squish(.data$a), collapse = " "))) %>%
      tidyr::unnest(.data$a)
  }

  df_cmd
}


apply_df_cmd_manip <- function(df_cmd_manip_string, df_cmd) {
  df_cmd <- df_cmd_manip_string %>% rlang::parse_expr() %>% rlang::eval_tidy()
}
generate_rec_na_cmd_table <- function(mapping) {
  # generates a row of a command table with the command to recode missing to -2,
  # labelled "FILTER"
  vars_to_exclude_na_to_filter <- c(
    mapping$mapping_file_attrs$not_miss_to_filter_vars,
    mapping$id_var,
    mapping$mapping_file_attrs$added_id_var
  )
  na_rec_vec <- mapping$mapping_file_attrs$miss_replace_lab_val
  tibble::tibble(
    sheet = "Config",
    action = "#RECNA",
    row = NA_character_,
    new_var = NA_character_,
    data = list(
      list(
        recode_na_exceptions = vars_to_exclude_na_to_filter,
        replace_val = unname(na_rec_vec),
        replace_label = names(na_rec_vec)
      )
    )
  )
}
generate_sheet_cmd_table <- function(mapping_file, sheet_cat, sheet_name) {
  switch (
    sheet_cat,
    "Variables" = mapp_var_sheet_cmd_table(mapping_file, sheet = sheet_name),
    "Label"     = mapp_vallab_sheet_cmd_table(mapping_file, sheet = sheet_name),
    "Free"      = mapp_free_sheet_cmd_table(mapping_file, sheet = sheet_name),
    "Verbatims" = mapp_verbatim_sheet_cmd_tbl(mapping_file, sheet = sheet_name)
  )

}
