#' Apply a command block to the mapping
#'
#' @param cdb `command_block` object
#' @param mapping mapping object
#' @param ... Arguments passed to method
#'
#' @export
#' @examples
#' mapping_file <- system.file("extdata", "mapping.xlsx", package = "datenanpassr")
#' spss_file <- system.file("extdata", "fake_survey.sav", package = "datenanpassr")
#' m <- Mapping$new(spss_file, mapping_file)
#' # Construct a command_block of the 10th line in m$cmd$df_cmd_raw:
#' cb <- m$cmd$df_cmd_raw %>%
#'   purrr::transpose() %>%
#'   .[[10]] %>%
#'   command_block() %>%
#'   parse_command_args()
#' # Generate command_blocks object:
#' cbs <- list(cb) %>%
#'   datenanpassr:::new_command_blocks(subclass = "unsafe")
#' # Apply it to the data:
#' m$modify_data(command_blocks = cbs)
#'
#' # The label of the variable in m$dat_mod was modified:
#' m$dat$q5
#' m$dat_mod$q5
apply_command <- function(cdb, mapping, ...) {
  UseMethod("apply_command")
}

# thanks to
# https://mirai-solutions.ch/techguides/advanced-usage-and-consistent-documentation.html#using-rdname-and-describein
# We can collect all the roxxygen `@param`s in one place:
#' @name apply_command_args
#' @rdname apply_command
#' @param x,xs,y,ys character string (vector) of variable names in `mapping$dat_mod`
#' @param v,v0,vs,vs0,vs2 Numeric value(s)
#' @param vallab,vallabs Value label(s)
#' @param varlab Character string containing a variable label
#' @param ex,ex_cond,ex_fun,ex_further_cond,ex_assign Character strings
#'   containing valid R expressions. They will be evaluated in
#'   `mapping$params$expr_eval_env` (see `gen_mapping_params()`).
#' @param filepath Character string containing valid file path
#' @param id Character string of the variable name of the id variable in `mapping$dat`.
#' @param id_list Vector of id values in `mapping$dat_mod[id]`.
#' @param sheet_name Sheet where the command is from in the `mapping$mapping_file`.
#' @param stata_index Ascending index for each of the #STATA commands in the Excel sheet.
#'
NULL
# see https://github.com/r-lib/tidyselect/issues/201#issuecomment-650547846:
utils::globalVariables("where")
#' @describeIn apply_command Replace missing values of the labelled variables in
#'   `mapping$dat_mod` (except those specified in `xs`) with the value `v`,
#'   labelled `vallab`.
#' @export
apply_command.cmd_recna_xcpt <- function(cdb, mapping, xs, v, vallab, ...) {
  # remove variable names not found in df:
  # TODO: think of cleaner way to do this:
  xs <- intersect(xs, names(mapping$dat_mod))
  mapping$dat_mod <- mapping$dat_mod %>%
    dplyr::mutate(
      dplyr::across(
        where(is.numeric) & !c(dplyr::one_of(xs)),
        ~ set_na_to_filter(.x, v, vallab)
      )
    )
}

#' @describeIn apply_command Save the data in `mapping$dat_mod` to a stata dta file.
#'   If `filename` is `NA`, the filepath is generated by:
#'   "stata_output_" + `sheet_name` + "_" + `stata_index`, + ".dta"
#' @export
apply_command.cmd_write_stata <- function(cdb, mapping, filepath, stata_index, sheet_name, xs, ...) {
  if (is.na(filepath)) {
    filepath <- paste0("stata_output_", sheet_name, "_", stata_index, ".dta")
  }
  if (is.na(xs)) {
    xs <- names(mapping$dat_mod)
  }
  haven::write_dta(mapping$dat_mod[xs], filepath)
  if (mapping$params$debug) {
    utils::browseURL(filepath)
    browser()
  }
}
#' @describeIn apply_command Execute R code
#' @export
apply_command.cmd_r <- function(cdb, mapping, ex, ...) {
  new_df <- ex %>%
    rlang::parse_expr() %>%
    eval_in_data(mapping)
  mapping$dat_mod <- dplyr::bind_cols(mapping$dat_mod, new_df)
}

#' @describeIn apply_command Execute the function named `ex_fun` and
#'   defined in the R script named `filepath`.
#' @export
apply_command.cmd_rfun <- function(cdb, mapping, filepath, ex_fun, ...) {
  if (!is.na(filepath)) {
    source(filepath, echo = FALSE)
  }

  mapping$dat_mod <- do.call(ex_fun, list(mapping$dat_mod))
}

#' @describeIn apply_command Split variable
#'
#' @export
apply_command.cmd_kg <- function(cdb, mapping, x, y, ...) {
  split_var <- mapping$dat_mod[[x]]
  by_var <- mapping$dat_mod[[y]]
  df <- data.frame(split_var, by_var) %>% purrr::set_names(~ c(x, y))
  # by_var <- rlang::as_string(rlang::expr(by_var))
  new_vars <- prepare_newvar_table(df, x, y)
  mapping$dat_mod[new_vars$new_varnames] <- new_vars %>%
    purrr::transpose() %>%
    # these 2 lines would do the same
    # rowwise() %>%
    # group_split() %>%
    # add the new variables one by one to the dataframe:
    purrr::reduce(split_cat_by_cat, x, y, .init = df) %>%
    dplyr::select(-dplyr::all_of(c(x, y)))
}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_drop <- function(cdb, mapping, xs, ...) {
  mapping$dat_mod[xs] <- NULL
}
#' @describeIn apply_command
#'
#' @export
apply_command.cmd_verbatim <- function(cdb, mapping,
                                       x,
                                       v,
                                       varlab,
                                       vs,
                                       vallabs,
                                       id_list,
                                       v0,
                                       ex_further_cond,
                                       id = mapping$params$id_var,
                                       ...) {
  vallabs_named <- purrr::set_names(vs, vallabs)
  v <- as.numeric(v)

  if (!x %in% names(mapping$dat_mod)) {
    mapping$dat_mod[[x]] <- v0
  }

  # keep variable label if it already exists:
  if (is.null(varlab)) {
    varlab <- attr(mapping$dat_mod[[x]], "label", exact = TRUE)
  }

  if (!is.na(ex_further_cond)) {
    further_ex_bool <- eval_in_data(rlang::parse_expr(ex_further_cond), mapping) %>%
      is_true()
  } else {
    further_ex_bool <- TRUE
  }

  mapping$dat_mod[[x]][mapping$dat_mod[[id]] %in% id_list & further_ex_bool] <- v
  mapping$dat_mod[[x]] <- haven::labelled(
    mapping$dat_mod[[x]],
    labels = vallabs_named,
    label = varlab
  )
}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_verbatim_custom <- function(
  cdb, mapping, x, v, varlab, vs, vallabs, id_list, v0, ex_further_cond, ex_assign,
  id = mapping$params$id_var, ...
) {
  vallabs_named <- purrr::set_names(vs, vallabs)

  if (!x %in% names(mapping$dat_mod)) {
    mapping$dat_mod[[x]] <- v0
  }

  # keep variable label if it already exists:
  if (is.null(varlab)) {
    varlab <- attr(mapping$dat_mod[[x]], "label", exact = TRUE)
  }

  if (!is.na(ex_further_cond)) {
    further_ex_bool <- eval_in_data(rlang::parse_expr(ex_further_cond), mapping) %>%
      is_true()
  } else {
    further_ex_bool <- rep(TRUE, nrow(mapping$dat_mod))
  }

  if (!is.na(ex_assign)) {
    ex_assign_vec <- eval_in_data(rlang::parse_expr(ex_assign), mapping)
    # don't take the variable label of the verbatim coding...:
    # varlab <- attr(ex_assign_vec, "label", exact = TRUE)
    # ... only keep the existing value labels:
    vallabs_named <- attr(ex_assign_vec, "labels")
  } else {
    ex_assign_vec <- rep(v, nrow(mapping$dat_mod))
  }

  id_list_existing <- intersect(id_list, mapping$dat[[id]])
  if (length(id_list_existing) < length(id_list)) {
    warning("there are id values in the verbatim sheet not in the data")
  }
  ex_row_indices <- match(id_list_existing, mapping$dat[[id]])
  assign_indices <- intersect(which(further_ex_bool), ex_row_indices)


  mapping$dat_mod[assign_indices, ][[x]] <- ex_assign_vec[assign_indices]
  mapping$dat_mod[[x]] <- haven::labelled(
    mapping$dat_mod[[x]],
    labels = vallabs_named,
    label = varlab
  )
}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_merge <- function(cdb, mapping, xs, filepath, id = mapping$params$id_var, ...) {
  # If `xs` isn't specified in Excel sheet, merge all variables in the file:
  if (length(xs) == 1 & is.na(xs[1])) {
    df_merge <- haven::read_sav(filepath)
  } else {
    df_merge <- haven::read_sav(filepath, col_select = !!c(id, xs))
  }
  id_vec <- mapping$dat_mod[[id]]
  if (!identical(
    sort(tablab::strip_attributes(df_merge[[id]])),
    sort(tablab::strip_attributes(id_vec))
  )
  ) {
    warning("The merged dataframe doesn't contain the same id values")
    df_merge <- df_merge[df_merge[[id]] %in% id_vec,]
  }

  # This kind of merging overwrites variables if existing:
  df_merge_sort <- tibble::tibble(id_vec) %>%
    dplyr::rename(!!id := id_vec) %>%
    dplyr::full_join(df_merge, by = id) %>%
    dplyr::select(-!!id)
  mapping$dat_mod <- mapping$dat_mod %>%
    dplyr::mutate(
      df_merge_sort
    )
}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_rename <- function(cdb, mapping, xs, ys, ...) {
  mapping$dat_mod <- mapping$dat_mod %>%
    dplyr::rename(!!!purrr::set_names(ys, xs))
}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_if <- function(cdb, mapping, x, ex_cond, ex, ...) {
  cond <- rlang::parse_expr(ex_cond)
  val <- rlang::parse_expr(ex)

  # add double NA column to data, if x doesn't exist yet (together with
  # the attributes copying below, this keeps the variable's labels if existing):
  if (!x %in% names(mapping$dat_mod)) {
    mapping$dat_mod[[x]] <- NA_real_
  }

  test <- eval_in_data(rlang::expr(datenanpassr::is_true(!!cond)), mapping)
  yes <- eval_in_data(rlang::expr(!!val), mapping)

  if (mapping$params$dyn_validate) {
    dyn_validate_cmd_if(test, yes, x, mapping)
  }

  no <- mapping$dat_mod[[x]]
  attributes(yes) <- attributes(no)

  mapping$dat_mod[[x]] <-
    data.table::fifelse(
      test,
      yes,
      no
    )
}
dyn_validate_cmd_if <- function(test, yes, x, mapping) {
  stopifnot(x %in% names(mapping$dat_mod))
  vec <- mapping$dat_mod[[x]]
  stopifnot(is.logical(test))
  stopifnot(typeof(yes) == typeof(vec))
  stopifnot(typeof(yes) %in% c("double", "character"))
}

eval_in_data <- function(ex, mapping) {
  rlang::eval_tidy(
    ex,
    env = list2env(mapping$dat_mod, parent = mapping$params$expr_eval_env)
  )
}

#' @describeIn apply_command
#'
#' @export
#' @importFrom rlang `%||%`
apply_command.cmd_comp <- function(cdb, mapping, x, ex, ...) {
  val <- rlang::parse_expr(ex)

  # add double NA column to data, if x doesn't exist yet (together with
  # the attributes copying below, this keeps the variable's labels if existing):
  if (!x %in% names(mapping$dat_mod)) {
    mapping$dat_mod[[x]] <- NA_real_
  }

  vec <- eval_in_data(rlang::expr(!!val), mapping)
  varlab <- labelled::var_label(vec) %||% labelled::var_label(mapping$dat_mod[[x]])
  vallabs <- labelled::val_labels(vec) %||% labelled::val_labels(mapping$dat_mod[[x]])
  if (is.logical(vec)) {
    vec <- as.integer(vec)
  }
  # attributes(vec) <- attributes(mapping$dat_mod[[x]])
  if (!is.null(varlab) | !is.null(vallabs)) {
    vec <- haven::labelled(
      vec,
      labels = vallabs,
      label = varlab
    )
  }

  mapping$dat_mod[[x]] <- vec
}
#' @describeIn apply_command
#'
#' @export
apply_command.cmd_compr <- apply_command.cmd_comp

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_set_lab <- function(cdb, mapping, x, varlab, ...) {
  vec <- mapping$dat_mod[[x]]
  mapping$dat_mod[[x]] <- haven::labelled(
    vec,
    labels = attr(vec, "labels"),
    label = varlab
  )
}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_newlab <- apply_command.cmd_set_lab

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_set_labs <- function(cdb, mapping, x, varlab, vs, vallabs, ...) {
  if (is.null(varlab)) {
    varlab <- attr(mapping$dat_mod[[x]], "label", exact = TRUE)
  }
  mapping$dat_mod[[x]] <- haven::labelled(
    mapping$dat_mod[[x]],
    labels = purrr::set_names(vs, vallabs),
    label = varlab
  )
}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_add_labs <- function(cdb, mapping, x, varlab = NULL, vs, vallabs, ...) {
  vec <- mapping$dat_mod[[x]]
  old_vallab_vec <- attr(vec, "labels")
  added_vallab_vec <- purrr::set_names(vs, vallabs)
  new_vallab_vec <- merge_vallabs(old_vallab_vec, added_vallab_vec)

  if (is.null(varlab)) {
    varlab <- attr(vec, "label", exact = TRUE)
  } else {
    varlab <- varlab
  }

  mapping$dat_mod[[x]] <- haven::labelled(
    vec,
    labels = new_vallab_vec,
    label = varlab
  )
}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_newvall <- apply_command.cmd_add_labs

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_rec <- function(cdb, mapping, x, y, varlab, vs0, vs, vs2, vallabs, ...) {
  if (is.na(varlab)) {
    varlab <- attr(mapping$dat_mod[[y]], "label", exact = TRUE)
  }

  if (is.na(x)) {
    x <- y
  }

  lb <- vs0
  vs <- vs
  ub <- vs2

  recode_df <-
    tibble::tibble(lb, ub = dplyr::coalesce(ub, lb), vs, vallabs) %>%
    dplyr::mutate(
      expr_str = paste0("(", y, " >= ", lb, " & ", y, " <= ", ub, ")")
    ) %>%
    dplyr::group_by(vs) %>%
    dplyr::summarise(
      expr_str = paste(.data$expr_str, collapse = " | "),
      vallabs = vallabs[1]
    )
  cond_statements <-
    recode_df %>%
    dplyr::select(vs, .data$expr_str) %>%
    purrr::pmap(
      function(vs, expr_str) rlang::quo(!!rlang::parse_expr(expr_str) ~ !!vs)
    )

  res_num <- rlang::expr(dplyr::case_when(!!!cond_statements)) %>% eval_in_data(mapping)
  if (x == y) {
    res_num <- dplyr::coalesce(res_num, mapping$dat_mod[[y]])
  }

  mapping$dat_mod[[x]] <- haven::labelled(
    res_num,
    labels = purrr::set_names(recode_df$vs, recode_df$vallabs),
    label = varlab
  )

}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_sumvar <- function(cdb, mapping, x, y, varlab, vs0, vs, vallabs, ...) {
  if (is.na(varlab)) {
    varlab <- attr(mapping$dat_mod[[y]], "label", exact = TRUE)
  }

  sum_var_vals_n_labs <- tibble::tibble(vs0, vs, vallabs) %>%
    dplyr::group_by(vs) %>%
    dplyr::summarise(
      val_lists = list(vs0),
      val_labs = dplyr::first(vallabs)
    )
  cond_statements <- purrr::map2(
    sum_var_vals_n_labs$val_lists,
    sum_var_vals_n_labs$vs,
    ~ rlang::expr(!!rlang::sym(y) %in% !!.x ~ !!.y)
  )

  vec_num <- rlang::expr(dplyr::case_when(!!!cond_statements)) %>% eval_in_data(mapping)

  mapping$dat_mod[[x]] <- haven::labelled(
    vec_num,
    labels = sum_var_vals_n_labs[-2] %>% dplyr::select(2, 1) %>% tibble::deframe(),
    label = varlab
  )


}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_dic <- function(cdb, mapping, x, y, ...) {
  vec <- mapping$dat_mod[[y]]

  varlab <- attr(vec, "label", exact = TRUE)
  vallabs <- attr(vec, "labels", exact = TRUE)

  if (!x %in% names(mapping$dat_mod)) {
    mapping$dat_mod[[x]] <- NA_real_
  }

  mapping$dat_mod[[x]] <- haven::labelled(
    mapping$dat_mod[[x]],
    labels = vallabs,
    label = varlab
  )

}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_autorec <- function(cdb, mapping, x, ...) {
  vec <- mapping$dat_mod[[x]]
  x_labelled <- labelled::to_labelled(as.factor(vec))
  labelled::var_label(x_labelled) <- attr(vec, "label", exact = TRUE)

  mapping$dat_mod[[x]] <- x_labelled

}

#' @describeIn apply_command
#'
#' @export
apply_command.cmd_str_to_num <- function(cdb, mapping, x, ...) {
  var <- mapping$dat_mod[[x]]
  mapping$dat_mod[[x]] <- haven::labelled(
    var %>% tablab::strip_attributes() %>% as.numeric(),
    label = attr(var, "label", exact = TRUE)
  )

}
