#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom DBI dbConnect
#' @importFrom DBI dbDisconnect
#' @importFrom DBI sqlInterpolate
#' @importFrom DBI dbExecute
#' @importFrom DBI dbGetQuery
#' @importFrom DBI dbWriteTable
#' @importFrom digest digest
#' @importFrom dplyr across
#' @importFrom dplyr add_count
#' @importFrom dplyr all_of
#' @importFrom dplyr anti_join
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr coalesce
#' @importFrom dplyr cur_data
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr group_by_all
#' @importFrom dplyr group_split
#' @importFrom dplyr if_any
#' @importFrom dplyr inner_join
#' @importFrom dplyr intersect
#' @importFrom dplyr lag
#' @importFrom dplyr left_join
#' @importFrom dplyr matches
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_all
#' @importFrom dplyr n
#' @importFrom dplyr one_of
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr row_number
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr setdiff
#' @importFrom dplyr setequal
#' @importFrom dplyr slice
#' @importFrom dplyr starts_with
#' @importFrom dplyr summarise
#' @importFrom dplyr tally
#' @importFrom dplyr transmute
#' @importFrom dplyr ungroup
#' @importFrom fs is_absolute_path
#' @importFrom fs path_dir
#' @importFrom qs qsave
#' @importFrom qs qread
#' @importFrom haven is.labelled
#' @importFrom haven labelled
#' @importFrom haven read_dta
#' @importFrom haven read_sav
#' @importFrom haven write_dta
#' @importFrom haven write_sav
#' @importFrom labelled to_labelled
#' @importFrom labelled val_labels
#' @importFrom labelled var_label
#' @importFrom labelled var_label<-
#' @importFrom lifecycle deprecated
#' @importFrom odbc odbc
#' @importFrom openxlsx2 wb_workbook
#' @importFrom openxlsx2 wb_add_worksheet
#' @importFrom openxlsx2 wb_add_data
#' @importFrom openxlsx2 wb_load
#' @importFrom openxlsx2 wb_read
#' @importFrom openxlsx2 wb_get_sheet_names
#' @importFrom powerjoin power_full_join
#' @importFrom powerjoin coalesce_yx
#' @importFrom powerjoin coalesce_xy
#' @importFrom purrr chuck
#' @importFrom purrr imap_dfr
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_dfc
#' @importFrom purrr map_dfr
#' @importFrom purrr map_if
#' @importFrom purrr map_lgl
#' @importFrom purrr map2
#' @importFrom purrr negate
#' @importFrom purrr pluck
#' @importFrom purrr pmap
#' @importFrom purrr reduce
#' @importFrom purrr set_names
#' @importFrom purrr transpose
#' @importFrom purrr walk
#' @importFrom purrr walk2
#' @importFrom readxl cell_cols
#' @importFrom readxl cell_limits
#' @importFrom readxl excel_sheets
#' @importFrom readxl read_xls
#' @importFrom readxl read_xlsx
#' @importFrom rlang := .data
#' @importFrom rlang `%||%`
#' @importFrom rlang eval_tidy
#' @importFrom rlang expr
#' @importFrom rlang is_empty
#' @importFrom rlang parse_expr
#' @importFrom rlang parse_exprs
#' @importFrom rlang quo
#' @importFrom rlang sym
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_extract_all
#' @importFrom stringr str_match
#' @importFrom stringr str_remove
#' @importFrom stringr str_remove_all
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_squish
#' @importFrom stringr str_sub
#' @importFrom stringr str_subset
#' @importFrom stringr str_trim
#' @importFrom tibble as_tibble
#' @importFrom tibble deframe
#' @importFrom tibble enframe
#' @importFrom tibble lst
#' @importFrom tibble tibble
#' @importFrom tidyr drop_na
#' @importFrom tidyr fill
#' @importFrom tidyr gather
#' @importFrom tidyr nest
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr tibble
#' @importFrom tidyr unnest
#' @importFrom utils browseURL
#' @importFrom utils modifyList
#' @importFrom withr with_options
#' @importFrom withr with_output_sink
#' @importFrom writexl write_xlsx
## usethis namespace: end
NULL
